// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UItes
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// tesPa
        /// </summary>
        public void tesPa()
        {
            #region Variable Declarations
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItemButton = this.UIMyCalculatorv1Window.UIItemButton;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem9Button = this.UIMyCalculatorv1Window.UIItem9Button;
            WpfButton uIItemButton2 = this.UIMyCalculatorv1Window.UIItemButton2;
            WpfButton uIItem6Button = this.UIMyCalculatorv1Window.UIItem6Button;
            WpfButton uIItem0Button = this.UIMyCalculatorv1Window.UIItem0Button;
            WpfButton uIItemButton3 = this.UIMyCalculatorv1Window.UIItemButton3;
            WpfButton uIItem3Button = this.UIMyCalculatorv1Window.UIItem3Button;
            WpfButton uIItemButton4 = this.UIMyCalculatorv1Window.UIItemButton4;
            WpfButton uIRButton = this.UIMyCalculatorv1Window.UIRButton;
            WpfButton uIOffButton = this.UIMyCalculatorv1Window.UIOffButton;
            #endregion

            // Last mouse action was not recorded.

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(9, 13));

            // Click '/' button
            Mouse.Click(uIItemButton, new Point(29, 14));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(22, 14));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(29, 25));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(22, 18));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(22, 18));

            // Click '+' button
            Mouse.Click(uIItemButton2, new Point(28, 22));

            // Click '6' button
            Mouse.Click(uIItem6Button, new Point(9, 6));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(56, 19));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(21, 13));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(26, 12));

            // Click '-' button
            Mouse.Click(uIItemButton3, new Point(30, 8));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(30, 11));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(52, 21));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(26, 21));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(33, 25));

            // Click '*' button
            Mouse.Click(uIItemButton4, new Point(34, 5));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(8, 18));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(49, 21));

            // Click 'R' button
            Mouse.Click(uIRButton, new Point(14, 15));

            // Click 'Off' button
            Mouse.Click(uIOffButton, new Point(51, 13));
        }
        
        #region Properties
        public UIMyCalculatorv1Window UIMyCalculatorv1Window
        {
            get
            {
                if ((this.mUIMyCalculatorv1Window == null))
                {
                    this.mUIMyCalculatorv1Window = new UIMyCalculatorv1Window();
                }
                return this.mUIMyCalculatorv1Window;
            }
        }
        #endregion
        
        #region Fields
        private UIMyCalculatorv1Window mUIMyCalculatorv1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIMyCalculatorv1Window : WpfWindow
    {
        
        public UIMyCalculatorv1Window()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MyCalculator v1";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MyCalculator v1");
            #endregion
        }
        
        #region Properties
        public WpfButton UIItem2Button
        {
            get
            {
                if ((this.mUIItem2Button == null))
                {
                    this.mUIItem2Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem2Button.SearchProperties[WpfButton.PropertyNames.Name] = "2";
                    this.mUIItem2Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem2Button;
            }
        }
        
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WpfButton.PropertyNames.Name] = "/";
                    this.mUIItemButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WpfButton UIItemButton1
        {
            get
            {
                if ((this.mUIItemButton1 == null))
                {
                    this.mUIItemButton1 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton1.SearchProperties[WpfButton.PropertyNames.Name] = "=";
                    this.mUIItemButton1.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton1;
            }
        }
        
        public WpfButton UIDelButton
        {
            get
            {
                if ((this.mUIDelButton == null))
                {
                    this.mUIDelButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIDelButton.SearchProperties[WpfButton.PropertyNames.Name] = "Del";
                    this.mUIDelButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIDelButton;
            }
        }
        
        public WpfButton UIItem9Button
        {
            get
            {
                if ((this.mUIItem9Button == null))
                {
                    this.mUIItem9Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem9Button.SearchProperties[WpfButton.PropertyNames.Name] = "9";
                    this.mUIItem9Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem9Button;
            }
        }
        
        public WpfButton UIItemButton2
        {
            get
            {
                if ((this.mUIItemButton2 == null))
                {
                    this.mUIItemButton2 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton2.SearchProperties[WpfButton.PropertyNames.Name] = "+";
                    this.mUIItemButton2.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton2;
            }
        }
        
        public WpfButton UIItem6Button
        {
            get
            {
                if ((this.mUIItem6Button == null))
                {
                    this.mUIItem6Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem6Button.SearchProperties[WpfButton.PropertyNames.Name] = "6";
                    this.mUIItem6Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem6Button;
            }
        }
        
        public WpfButton UIItem0Button
        {
            get
            {
                if ((this.mUIItem0Button == null))
                {
                    this.mUIItem0Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem0Button.SearchProperties[WpfButton.PropertyNames.Name] = "0";
                    this.mUIItem0Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem0Button;
            }
        }
        
        public WpfButton UIItemButton3
        {
            get
            {
                if ((this.mUIItemButton3 == null))
                {
                    this.mUIItemButton3 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton3.SearchProperties[WpfButton.PropertyNames.Name] = "-";
                    this.mUIItemButton3.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton3;
            }
        }
        
        public WpfButton UIItem3Button
        {
            get
            {
                if ((this.mUIItem3Button == null))
                {
                    this.mUIItem3Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem3Button.SearchProperties[WpfButton.PropertyNames.Name] = "3";
                    this.mUIItem3Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem3Button;
            }
        }
        
        public WpfButton UIItemButton4
        {
            get
            {
                if ((this.mUIItemButton4 == null))
                {
                    this.mUIItemButton4 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton4.SearchProperties[WpfButton.PropertyNames.Name] = "*";
                    this.mUIItemButton4.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton4;
            }
        }
        
        public WpfButton UIRButton
        {
            get
            {
                if ((this.mUIRButton == null))
                {
                    this.mUIRButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIRButton.SearchProperties[WpfButton.PropertyNames.Name] = "R";
                    this.mUIRButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIRButton;
            }
        }
        
        public WpfButton UIOffButton
        {
            get
            {
                if ((this.mUIOffButton == null))
                {
                    this.mUIOffButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIOffButton.SearchProperties[WpfButton.PropertyNames.Name] = "Off";
                    this.mUIOffButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIOffButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIItem2Button;
        
        private WpfButton mUIItemButton;
        
        private WpfButton mUIItemButton1;
        
        private WpfButton mUIDelButton;
        
        private WpfButton mUIItem9Button;
        
        private WpfButton mUIItemButton2;
        
        private WpfButton mUIItem6Button;
        
        private WpfButton mUIItem0Button;
        
        private WpfButton mUIItemButton3;
        
        private WpfButton mUIItem3Button;
        
        private WpfButton mUIItemButton4;
        
        private WpfButton mUIRButton;
        
        private WpfButton mUIOffButton;
        #endregion
    }
}
